//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FASTWSv1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReasonCode
    {
        public int ReasonCodeID { get; set; }
        public string ReasonCode1 { get; set; }
    }
}
